// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanDienThoai.Models;

#nullable disable

namespace WebBanDienThoai.Migrations
{
    [DbContext(typeof(QLBanDTContext))]
    partial class QLBanDTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebBanDienThoai.Models.Nguoidung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"), 1L, 1);

                    b.Property<string>("Anhdaidien")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IDQuyen")
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PhanQuyenIDQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK_Khachhang");

                    b.HasIndex("PhanQuyenIDQuyen");

                    b.ToTable("Nguoidung", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.PhanQuyen", b =>
                {
                    b.Property<int>("IDQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDQuyen");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDQuyen"), 1L, 1);

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDQuyen");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TChiTietHdb", b =>
                {
                    b.Property<string>("SoHdb")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDB");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("KhuyenMai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Slban")
                        .HasColumnType("int")
                        .HasColumnName("SLBan");

                    b.HasKey("SoHdb", "MaSp");

                    b.HasIndex("MaSp");

                    b.ToTable("tChiTietHDB", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TChiTietHdn", b =>
                {
                    b.Property<string>("SoHdn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDN");

                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<string>("KhuyenMai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Slnhap")
                        .HasColumnType("int")
                        .HasColumnName("SLNhap");

                    b.HasKey("SoHdn", "MaSp");

                    b.HasIndex("MaSp");

                    b.ToTable("tChiTietHDN", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THang", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHang")
                        .HasName("PK_tTheLoai");

                    b.ToTable("tHang", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THoaDonBan", b =>
                {
                    b.Property<string>("SoHdb")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDB");

                    b.Property<int?>("MaKhNavigationMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayBan")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongHdb")
                        .HasColumnType("money")
                        .HasColumnName("TongHDB");

                    b.HasKey("SoHdb");

                    b.HasIndex("MaKhNavigationMaNguoiDung");

                    b.ToTable("tHoaDonBan", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THoaDonNhap", b =>
                {
                    b.Property<string>("SoHdn")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("SoHDN");

                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("MaNccNavigationMaNcc")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongHdn")
                        .HasColumnType("money")
                        .HasColumnName("TongHDN");

                    b.HasKey("SoHdn");

                    b.HasIndex("MaNccNavigationMaNcc");

                    b.ToTable("tHoaDonNhap", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TNhaCungCap", b =>
                {
                    b.Property<string>("MaNcc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaNCC");

                    b.Property<string>("TenNcc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenNCC");

                    b.HasKey("MaNcc");

                    b.ToTable("tNhaCungCap", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TSp", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaSP");

                    b.Property<byte[]>("Anh")
                        .HasColumnType("image");

                    b.Property<decimal?>("DonGiaBan")
                        .HasColumnType("money");

                    b.Property<decimal?>("DonGiaNhap")
                        .HasColumnType("money");

                    b.Property<string>("MaHang")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHangNavigationMaHang")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaTl")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTL");

                    b.Property<string>("MaTlNavigationMaTl")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK_tSach");

                    b.HasIndex("MaHangNavigationMaHang");

                    b.HasIndex("MaTlNavigationMaTl");

                    b.ToTable("tSP", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TTheLoai", b =>
                {
                    b.Property<string>("MaTl")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaTL");

                    b.Property<string>("TenTl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTL");

                    b.HasKey("MaTl")
                        .HasName("PK_tNhaXuatBan");

                    b.ToTable("tTheLoai", (string)null);
                });

            modelBuilder.Entity("WebBanDienThoai.Models.Nguoidung", b =>
                {
                    b.HasOne("WebBanDienThoai.Models.PhanQuyen", "PhanQuyen")
                        .WithMany("Nguoidung")
                        .HasForeignKey("PhanQuyenIDQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TChiTietHdb", b =>
                {
                    b.HasOne("WebBanDienThoai.Models.TSp", "MaSpNavigation")
                        .WithMany("TChiTietHdbs")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanDienThoai.Models.THoaDonBan", "SoHdbNavigation")
                        .WithMany("TChiTietHdbs")
                        .HasForeignKey("SoHdb")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaSpNavigation");

                    b.Navigation("SoHdbNavigation");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TChiTietHdn", b =>
                {
                    b.HasOne("WebBanDienThoai.Models.TSp", "MaSpNavigation")
                        .WithMany("TChiTietHdns")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanDienThoai.Models.THoaDonNhap", "SoHdnNavigation")
                        .WithMany("TChiTietHdns")
                        .HasForeignKey("SoHdn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaSpNavigation");

                    b.Navigation("SoHdnNavigation");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THoaDonBan", b =>
                {
                    b.HasOne("WebBanDienThoai.Models.Nguoidung", "MaKhNavigation")
                        .WithMany("Donhang")
                        .HasForeignKey("MaKhNavigationMaNguoiDung");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THoaDonNhap", b =>
                {
                    b.HasOne("WebBanDienThoai.Models.TNhaCungCap", "MaNccNavigation")
                        .WithMany("THoaDonNhaps")
                        .HasForeignKey("MaNccNavigationMaNcc");

                    b.Navigation("MaNccNavigation");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TSp", b =>
                {
                    b.HasOne("WebBanDienThoai.Models.THang", "MaHangNavigation")
                        .WithMany("TSp")
                        .HasForeignKey("MaHangNavigationMaHang");

                    b.HasOne("WebBanDienThoai.Models.TTheLoai", "MaTlNavigation")
                        .WithMany("TSp")
                        .HasForeignKey("MaTlNavigationMaTl");

                    b.Navigation("MaHangNavigation");

                    b.Navigation("MaTlNavigation");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.Nguoidung", b =>
                {
                    b.Navigation("Donhang");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.PhanQuyen", b =>
                {
                    b.Navigation("Nguoidung");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THang", b =>
                {
                    b.Navigation("TSp");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THoaDonBan", b =>
                {
                    b.Navigation("TChiTietHdbs");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.THoaDonNhap", b =>
                {
                    b.Navigation("TChiTietHdns");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TNhaCungCap", b =>
                {
                    b.Navigation("THoaDonNhaps");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TSp", b =>
                {
                    b.Navigation("TChiTietHdbs");

                    b.Navigation("TChiTietHdns");
                });

            modelBuilder.Entity("WebBanDienThoai.Models.TTheLoai", b =>
                {
                    b.Navigation("TSp");
                });
#pragma warning restore 612, 618
        }
    }
}
